name: Build and Push

on:
  push:
    tags:
      - 'v*.*.*-*'

jobs:
  build_and_release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Set GitHub tag in env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build docker image
        run: ./app.sh build $RELEASE_VERSION

      - name: Test docker image
        run: ./app.sh test $RELEASE_VERSION

      - name: Push docker image
        run: |
          docker login -u=${{secrets.DOCKER_USERNAME}} -p=${{secrets.DOCKER_PASSWORD}}
          ./app.sh push $RELEASE_VERSION
          docker logout
